image: node:14-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm build

test1:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  script:
      - node test/testInterpreter.js 

test2:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  script:
      - node mqtt.js 

test3:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
    - variables:
      port: 8082
  script:
      - npm i -g mocha
      - npm i -g websocket
      - sleep 40
      - cd test
      - npm test