image: node:14-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm build

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    WebSocket: "ws://localhost:8082"
  script: 
      - npm i -g mocha
      - curl start powershell
      - invoke-expression 'cmd /c start powershell -NoExit -Command {node mqtt.js}'
      - start powershell {node testInterpreter.js}
      - cd test
      - npm test