image: node:14-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm build

test3:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    WebSocket: "ws://localhost:8082"
  script: |
      - node mqtt.js
  script2: |
      - cd test
      - node testInterpreter.js
  script3: 
      - npm i -g mocha
      - npm i -g websocket
      - cd test
      - npm test